In [1]:
import datasets_adapters  # providing adapters for Dataset operations
import verifiers  # providing verifier for models

2024-05-13 19:36:25.554091: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-13 19:36:25.555862: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-13 19:36:25.584533: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-13 19:36:25.585438: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-13 19:36:26.053318: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
hispanic_kyc = datasets_adapters.KYCDatasetAdapter(
    sources_path='datasets/hispanic/files',
    destination_path='data/hispanic/',
    accordande_file_path='datasets/hispanic/hispanics_kyc_dataset.csv',
    dataset_name='Hispanian KYC',
)
hispanic_kyc.prepare_data()

Destination folder: hispanic                      deleted...created
    Processing combination 3...                   completed
    Processing combination 5...                   completed
    Processing combination 4...                   completed
    Processing combination 2...                   completed
    Processing combination 1...                   completed

In [3]:
hispanic_kyc.accordance

,id,age,gender,country,id_1,id_2,selfie_1,selfie_2,selfie_3,selfie_4,selfie_5,selfie_6,selfie_7,selfie_8,selfie_9,selfie_10,selfie_11,selfie_12,selfie_13
0,1,24,MALE,VE,1_ID_1.jpg,1_ID_2.jpg,1_Selfie_1.jpg,1_Selfie_1.jpg,1_Selfie_3.jpg,1_Selfie_4.jpg,1_Selfie_5.jpg,1_Selfie_6.jpg,1_Selfie_7.jpg,1_Selfie_8.jpg,1_Selfie_9.jpg,1_Selfie_10.jpg,1_Selfie_11.jpg,1_Selfie_12.jpg,1_Selfie_13.jpg
1,2,35,FEMALE,US,2_ID_1.jpg,2_ID_2.jpg,2_Selfie_1.jpg,2_Selfie_1.jpg,2_Selfie_3.jpg,2_Selfie_4.jpg,2_Selfie_5.jpg,2_Selfie_6.jpg,2_Selfie_7.jpg,2_Selfie_8.jpg,2_Selfie_9.jpg,2_Selfie_10.jpg,2_Selfie_11.jpg,2_Selfie_12.jpg,2_Selfie_13.jpg
2,3,24,MALE,MX,3_ID_1.jpg,3_ID_2.jpg,3_Selfie_1.jpg,3_Selfie_1.jpg,3_Selfie_3.jpg,3_Selfie_4.jpg,3_Selfie_5.jpg,3_Selfie_6.jpg,3_Selfie_7.jpg,3_Selfie_8.jpg,3_Selfie_9.jpg,3_Selfie_10.jpg,3_Selfie_11.jpg,3_Selfie_12.jpg,3_Selfie_13.jpg
3,4,42,FEMALE,DO,4_ID_1.jpg,4_ID_2.jpg,4_Selfie_1.jpg,4_Selfie_1.jpg,4_Selfie_3.jpg,4_Selfie_4.jpg,4_Selfie_5.jpg,4_Selfie_6.jpg,4_Selfie_7.jpg,4_Selfie_8.jpg,4_Selfie_9.jpg,4_Selfie_10.jpg,4_Selfie_11.jpg,4_Selfie_12.jpg,4_Selfie_13.jpg
4,5,29,MALE,GT,5_ID_1.jpg,5_ID_2.jpg,5_Selfie_1.jpg,5_Selfie_1.jpg,5_Selfie_3.jpg,5_Selfie_4.jpg,5_Selfie_5.jpg,5_Selfie_6.jpg,5_Selfie_7.jpg,5_Selfie_8.jpg,5_Selfie_9.jpg,5_Selfie_10.jpg,5_Selfie_11.jpg,5_Selfie_12.jpg,5_Selfie_13.jpg

In [4]:
asian_kyc = datasets_adapters.KYCDatasetAdapter(
    sources_path='datasets/asian/files',
    destination_path='data/asian/',
    accordande_file_path='datasets/asian/asian_kyc_dataset.csv',
    dataset_name='Asian KYC',
)
asian_kyc.prepare_data()

Destination folder: asian                         deleted...created
    Processing combination 3...                   completed
    Processing combination 5...                   completed
    Processing combination 4...                   completed
    Processing combination 2...                   completed
    Processing combination 1...                   completed

In [5]:
asian_kyc.accordance

,id,age,gender,country,ethnicity,id_1,id_2,selfie_1,selfie_2,selfie_3,selfie_4,selfie_5,selfie_6,selfie_7,selfie_8,selfie_9,selfie_10,selfie_11,selfie_12,selfie_13
0,1,29,FEMALE,ID,East Asia,1_ID_1.jpg,1_ID_2.jpg,1_Selfie_1.jpg,1_Selfie_1.jpg,1_Selfie_3.jpg,1_Selfie_4.jpg,1_Selfie_5.jpg,1_Selfie_6.jpg,1_Selfie_7.jpg,1_Selfie_8.jpg,1_Selfie_9.jpg,1_Selfie_10.jpg,1_Selfie_11.jpg,1_Selfie_12.jpg,1_Selfie_13.jpg
1,2,19,MALE,IN,South Asia,2_ID_1.jpg,2_ID_2.jpg,2_Selfie_1.jpg,2_Selfie_1.jpg,2_Selfie_3.jpg,2_Selfie_4.jpg,2_Selfie_5.jpg,2_Selfie_6.jpg,2_Selfie_7.jpg,2_Selfie_8.jpg,2_Selfie_9.jpg,2_Selfie_10.jpg,2_Selfie_11.jpg,2_Selfie_12.jpg,2_Selfie_13.jpg
2,3,30,MALE,VN,East Asia,3_ID_1.jpg,3_ID_2.jpg,3_Selfie_1.jpg,3_Selfie_1.jpg,3_Selfie_3.jpg,3_Selfie_4.jpg,3_Selfie_5.jpg,3_Selfie_6.jpg,3_Selfie_7.jpg,3_Selfie_8.jpg,3_Selfie_9.jpg,3_Selfie_10.jpg,3_Selfie_11.jpg,3_Selfie_12.jpg,3_Selfie_13.jpg
3,4,23,FEMALE,MA,Middle East,4_ID_1.jpg,4_ID_2.jpg,4_Selfie_1.jpg,4_Selfie_1.jpg,4_Selfie_3.jpg,4_Selfie_4.jpg,4_Selfie_5.jpg,4_Selfie_6.jpg,4_Selfie_7.jpg,4_Selfie_8.jpg,4_Selfie_9.jpg,4_Selfie_10.jpg,4_Selfie_11.jpg,4_Selfie_12.jpg,4_Selfie_13.jpg
4,5,25,MALE,EG,Middle East,5_ID_1.jpg,5_ID_2.jpg,5_Selfie_1.jpg,5_Selfie_1.jpg,5_Selfie_3.jpg,5_Selfie_4.jpg,5_Selfie_5.jpg,5_Selfie_6.jpg,5_Selfie_7.jpg,5_Selfie_8.jpg,5_Selfie_9.jpg,5_Selfie_10.jpg,5_Selfie_11.jpg,5_Selfie_12.jpg,5_Selfie_13.jpg

In [6]:
vggface_model_verifier = verifiers.ModelVerifier('VGG-Face')
ghostfacenets_model_verifier = verifiers.ModelVerifier('GhostFaceNet')

In [7]:
vggface_model_verifier.execute(hispanic_kyc)

Verification VGG-Face on Hispanian KYC

100%|██████████| 70/70 [09:10<00:00,  7.87s/it]

           VGG-Face:Hispanian KYC
tp                      55.000000
tn                     253.000000
fp                      32.000000
fn                      10.000000
accuracy                 0.880000
recall                   0.846154
fpr                      0.112281
precision                0.632184
f_score                  0.723684

In [8]:
ghostfacenets_model_verifier.execute(hispanic_kyc)

Verification GhostFaceNet on Hispanian KYC

100%|██████████| 70/70 [07:59<00:00,  6.85s/it]

           GhostFaceNet:Hispanian KYC
tp                          41.000000
tn                         279.000000
fp                           6.000000
fn                          24.000000
accuracy                     0.914286
recall                       0.630769
fpr                          0.021053
precision                    0.872340
f_score                      0.732143

In [9]:
vggface_model_verifier.execute(asian_kyc)

Verification VGG-Face on Asian KYC

100%|██████████| 70/70 [09:01<00:00,  7.74s/it]

           VGG-Face:Asian KYC
tp                  29.000000
tn                 181.000000
fp                  49.000000
fn                   9.000000
accuracy             0.783582
recall               0.763158
fpr                  0.213043
precision            0.371795
f_score              0.500000

In [10]:
ghostfacenets_model_verifier.execute(asian_kyc)

Verification GhostFaceNet on Asian KYC

100%|██████████| 70/70 [07:52<00:00,  6.75s/it]

           GhostFaceNet:Asian KYC
tp                      17.000000
tn                     204.000000
fp                      26.000000
fn                      21.000000
accuracy                 0.824627
recall                   0.447368
fpr                      0.113043
precision                0.395349
f_score                  0.419753